import GlobalProvider from "@/components/application/GlobalProvider";
import "./globals.css";
import { Assistant } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";

import { ToastContainer } from "react-toastify";

import AuthWrapper from "@/components/application/auth/AuthWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const assistantFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${assistantFont.className} antialiased`}>
        <GlobalProvider>
          <ToastContainer />

          {children}

          {process.env.NODE_ENV === "production" && <SpeedInsights />}
          {/* 3. Render the wrapper instead of direct Login */}

          <AuthWrapper />
        </GlobalProvider>
      </body>
    </html>
  );
}
